apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nodejs
        image: bharath0812/java:11.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
 name: httpdservice
spec:
 type: NodePort
 selector:
   app: webapp
 ports:
   - port: 8088
     targetPort: 5000
     nodePort: 32140
     protocol: TCP
